---
- name: Generate Cloudera auto TLS files
  hosts: all
  become: yes

  vars:
    cert_dir: "/var/lib/cloudera-scm-agent/agent-cert"
    fqdn: "{{ inventory_hostname }}"
    host_cert: "{{ cert_dir }}/{{ fqdn }}.pem"
    host_key: "{{ cert_dir }}/{{ fqdn }}.key"
    ca_chain: "{{ cert_dir }}/ca_chain.pem"
    ca_cert: "{{ cert_dir }}/ca_cert.pem"
    host_key_pw: "changeit"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ cert_dir }}"
        state: directory
        mode: '0755'

    # --------------------------------
    # 1. Generate cm-auto-host_key.pem
    # --------------------------------
    - name: Copy host private key cm-auto-host_key.pem
      copy:
        src: "{{ host_key }}"
        dest: "{{ cert_dir }}/cm-auto-host_key.pem"
        mode: '0600'

    - name: Generate cm-auto-host_key_cert_chain.pem (host.pem + ca_chain)
      shell: |
        cat "{{ host_cert }}" "{{ ca_chain }}" > "{{ cert_dir }}/cm-auto-host_key_cert_chain.pem"
      args:
        executable: /bin/bash

    # ---------------------------------------
    # 2. Generate cm-auto-host_cert_chain.pem
    # ---------------------------------------
    - name: Generate cm-auto-host_cert_chain.pem (host.pem + ca_chain)
      shell: |
        cat "{{ host_cert }}" "{{ ca_chain }}" > "{{ cert_dir }}/cm-auto-host_cert_chain.pem"
      args:
        executable: /bin/bash

    # --------------------------------------
    # 3. Generate cm-auto-global_cacerts.pem
    # --------------------------------------
    - name: Copy CA chain → cm-auto-global_cacerts.pem
      copy:
        src: "{{ ca_chain }}"
        dest: "{{ cert_dir }}/cm-auto-global_cacerts.pem"
        mode: '0644'

    # -------------------------------
    # 4. Generate in-cluster CA files
    # -------------------------------
    - name: Copy in-cluster CA cert
      copy:
        src: "{{ ca_cert }}"
        dest: "{{ cert_dir }}/cm-auto-in_cluster_ca_cert.pem"
        mode: '0644'

    - name: Copy truststore (CA chain)
      copy:
        src: "{{ ca_chain }}"
        dest: "{{ cert_dir }}/cm-auto-in_cluster_truststore.jks"
        mode: '0644'

    # ------------------------------------
    # 5. Generate cm-auto-host_keystore.jks
    # ------------------------------------
    - name: Generate PKCS12 first
      shell: |
        openssl pkcs12 -export \
            -in "{{ host_cert }}" \
            -inkey "{{ host_key }}" \
            -certfile "{{ ca_chain }}" \
            -passout pass:{{ host_key_pw }} \
            -out "{{ cert_dir }}/host_bundle.p12"
      args:
        executable: /bin/bash

    - name: Generate cm-auto-host_keystore.jks
      shell: |
        keytool -importkeystore \
          -srckeystore "{{ cert_dir }}/host_bundle.p12" \
          -srcstoretype PKCS12 \
          -srcstorepass "{{ host_key_pw }}" \
          -destkeystore "{{ cert_dir }}/cm-auto-host_keystore.jks" \
          -deststorepass "{{ host_key_pw }}"
      args:
        executable: /bin/bash

    # ----------------------------
    # 6. Write password file
    # ----------------------------
    - name: Write cm-auto-host_key.pw
      copy:
        dest: "{{ cert_dir }}/cm-auto-host_key.pw"
        content: "{{ host_key_pw }}"
        mode: '0600'

    # -----------------------------------
    # 7. Generate global truststore (JKS)
    # -----------------------------------
    - name: Generate cm-auto-global_truststore.jks
      shell: |
        keytool -import \
          -file "{{ ca_chain }}" \
          -alias cm-auto-ca \
          -keystore "{{ cert_dir }}/cm-auto-global_truststore.jks" \
          -storepass "{{ host_key_pw }}" -noprompt
      args:
        executable: /bin/bash

    # ------------------------------------------------
    # 8. Generate dep-host_key_cert_chain_decrypted.pem
    # ------------------------------------------------
    - name: Generate decrypted host key chain
      shell: |
        cat "{{ host_key }}" "{{ host_cert }}" "{{ ca_chain }}" > "{{ cert_dir }}/dep-host_key_cert_chain_decrypted.pem"
      args:
        executable: /bin/bash

