---
- name: OS tuning (swappiness, THP, IPv6, SELinux, disable unused services)
  hosts: cluster
  become: yes
  tasks:
    - name: Ensure vm.swappiness = 1 (persistent & runtime)
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "1"
        state: present
        sysctl_set: true
        reload: true
      ignore_errors: true

    - name: Disable IPv6 via sysctl (all/default/lo)
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        sysctl_set: true
        reload: true
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Disable THP at runtime if needed
      shell: "echo never > {{ item }}"
      args:
        executable: /bin/bash
      loop: "{{ thp_paths }}"
      when: item is file
      changed_when: false
      ignore_errors: true


    - name: Disable THP runtime
      shell: |
        if [ -f /sys/kernel/mm/transparent_hugepage/enabled ]; then
          echo never > /sys/kernel/mm/transparent_hugepage/enabled
        fi
        if [ -f /sys/kernel/mm/transparent_hugepage/defrag ]; then
          echo never > /sys/kernel/mm/transparent_hugepage/defrag
        fi
      args:
        executable: /bin/bash


    - name: Ensure rc.local is executable
      file:
        path: /etc/rc.d/rc.local
        mode: '0755'
      ignore_errors: true


    - name: Set SELinux to permissive (runtime and persistent)
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      ignore_errors: true

    - name: Disable and stop unnecessary services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - bluetooth
        - cups
        - postfix
      ignore_errors: true 
      register: disabled_services

    - name: Show services disabled
      debug:
        var: disabled_services.results