# ozone_http_signature_secret.yml
---
- name: Compute or read the shared secret on a seed host, then distribute as facts
  hosts: cluster
  become: true
  gather_facts: false
  vars:
    dir_path: /etc/ozone
    secret_path: /etc/ozone/http-signature.secret
    service_user: ozone
    fallback_group: hadoop
  tasks:
    - name: Pick seed host
      set_fact:
        seed_host: "{{ groups['cluster'][0] }}"
      run_once: true

    - name: Ensure {{ dir_path }} exists on seed (for first creation)
      file:
        path: "{{ dir_path }}"
        state: directory
        owner: root
        group: "{{ fallback_group }}"
        mode: "0750"
      delegate_to: "{{ seed_host }}"
      run_once: true

    - name: Check if secret exists on seed
      stat:
        path: "{{ secret_path }}"
      register: seed_secret_stat
      delegate_to: "{{ seed_host }}"
      run_once: true

    - name: Read existing secret from seed
      slurp:
        path: "{{ secret_path }}"
      register: seed_secret_slurp
      when: seed_secret_stat.stat.exists
      delegate_to: "{{ seed_host }}"
      run_once: true

    - name: Generate secret on seed if absent (base64/32B)
      command: "openssl rand -base64 32"
      register: gen_secret
      when: not seed_secret_stat.stat.exists
      delegate_to: "{{ seed_host }}"
      run_once: true

    - name: Distribute secret value as a fact on every host
      set_fact:
        http_signature_secret: >-
          {{ (seed_secret_slurp.content | b64decode)
             if (seed_secret_stat.stat.exists)
             else gen_secret.stdout }}
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['cluster'] }}"
      run_once: true

- name: Create dir, install secret, set perms, restorecon, test
  hosts: cluster
  become: true
  gather_facts: true
  vars:
    dir_path: /etc/ozone
    secret_path: /etc/ozone/http-signature.secret
    service_user: ozone
    fallback_group: hadoop
  tasks:
    - name: Pick service group (prefer 'ozone', else 'hadoop')
      shell: "getent group {{ service_user }} >/dev/null 2>&1"
      register: ozone_group_check
      changed_when: false
      failed_when: false

    - set_fact:
        service_group: "{{ service_user if ozone_group_check.rc == 0 else fallback_group }}"

    - name: Ensure directory exists with correct perms
      file:
        path: "{{ dir_path }}"
        state: directory
        owner: root
        group: "{{ service_group }}"
        mode: "0750"

    - name: Install shared secret with correct perms
      copy:
        dest: "{{ secret_path }}"
        content: "{{ http_signature_secret }}"
        owner: root
        group: "{{ service_group }}"
        mode: "0640"

    - name: restorecon if SELinux enabled
      command: "restorecon -v {{ secret_path }}"
      changed_when: false
      failed_when: false
      when:
        - ansible_selinux is defined
        - ansible_selinux.status|default('disabled') == 'enabled'

    - name: Test read as service user
      command: "head -c 1 {{ secret_path }}"
      become_user: "{{ service_user }}"
      changed_when: false